<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
<meta name="google-site-verification" content="24bexHYipn300Q4f0nulYjYYbgf7ctTltjfUrB19GEQ" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta name="description" content="With offices in Bradford, Newcastle and Glasgow our aim is to be the first choice law firm for property and litigation services for the UK lending market." />
<title>Optima Legal - Optima Legal</title>

<link rel="alternate" type="application/rss+xml" title="Optima Legal RSS2 Feed" href="http://360.optimalegal.co.uk/?feed=rss2" />
<link rel="pingback" href="http://360.optimalegal.co.uk/xmlrpc.php" />


<link rel="stylesheet" href="http://360.optimalegal.co.uk/wp-content/themes/twicet/prettyPhoto/css/prettyPhoto.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="http://360.optimalegal.co.uk/wp-content/themes/twicet/style.css" type="text/css" media="screen" />

 
<link rel="stylesheet" href="http://360.optimalegal.co.uk/wp-content/themes/twicet/css/style1.css" type="text/css" media="screen" />
<meta name="robots" content="index, follow" />
<link rel='stylesheet' id='wp-email-css'  href='http://360.optimalegal.co.uk/wp-content/plugins/wp-email/email-css.css?ver=2.50' type='text/css' media='all' />
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-includes/js/jquery/jquery.js?ver=1.3.2'></script>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-includes/js/jquery/jquery.form.js?ver=2.02m'></script>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-content/plugins/mailchimp/js/mailchimp.js?ver=2.9.2'></script>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-content/themes/twicet/js/custom.js?ver=2.9.2'></script>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-content/themes/twicet/prettyPhoto/js/jquery.prettyPhoto.js?ver=2.9.2'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://360.optimalegal.co.uk/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://360.optimalegal.co.uk/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='Optima Legal' href='http://360.optimalegal.co.uk' />

<script type="text/javascript">
var mc_ajax_url = "http://360.optimalegal.co.uk/wp-content/plugins/mailchimp/mailchimp_ajax.php";
</script><link rel="stylesheet" href="http://360.optimalegal.co.uk/wp-content/plugins/wp-page-numbers/tiny/wp-page-numbers.css" type="text/css" media="screen" />
	<!-- Generated by Simple Tags 1.7.4.4 - http://wordpress.org/extend/plugins/simple-tags -->
	<meta name="keywords" content="Law, Mortgage, Debt, Litigation, Property, Commercial, Credit, Repossession, Professional Negligence, Risk, Conveyancing, Remortgage, Consumer credit, Shortfall, Enforcement, Secured, Civil procedure, Insolvency, TCF, Contentious, Contributory Negligence, Mortgage arrears, Repossessed, Homeowner and debtor protection bill" />

<meta name="twicet1" content="1" />
<meta name="twicet2" content="10000" />
<meta name="twicet3" content="http://360.optimalegal.co.uk/wp-content/themes/twicet" />
<meta name="twicet4" content="" />
<meta name="twicet5" content="7000" />
<!--[if IE 6]>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-content/themes/twicet/js/dd_belated_png.js'></script>
<script>DD_belatedPNG.fix('.ie6fix');</script>
<![endif]-->

</head>


<body id="frontpage">
<div class="wrap_all">
    <div id="top">
	  <div id="head"> 
      		<div id="topArea">
           <div id="logoHolder"><a href="http://360.optimalegal.co.uk/"><img border="0" src="http://360.optimalegal.co.uk/wp-content/themes/twicet/images/logo.gif" width="318" height="67" alt="Specialist Lawyers to the Lending Sector - Optima Legal" /></a></div>
                        <div id="searchHolder"><form method="get" id="searchform" action="http://360.optimalegal.co.uk/">
<input type="text" maxlength="26" value="" name="s" id="searchAr" />
<input type="submit" id="searchsubmit"  value="" />

</form>
</div>
			</div>			
            <div class="navwrap">	
                <ul id="nav">
                <li class="page_item page-item-2"><a href="http://360.optimalegal.co.uk/?page_id=2" title="About us">About us</a>
<ul>
	<li class="page_item page-item-29"><a href="http://360.optimalegal.co.uk/?page_id=29" title="The firm">The firm</a></li>
	<li class="page_item page-item-23"><a href="http://360.optimalegal.co.uk/?page_id=23" title="Property services">Property services</a></li>
	<li class="page_item page-item-4"><a href="http://360.optimalegal.co.uk/?page_id=4" title="Litigation services">Litigation services</a>
	<ul>
		<li class="page_item page-item-9"><a href="http://360.optimalegal.co.uk/?page_id=9" title="Pre legal">Pre legal</a></li>
		<li class="page_item page-item-19"><a href="http://360.optimalegal.co.uk/?page_id=19" title="Recoveries litigation">Recoveries litigation</a></li>
		<li class="page_item page-item-16"><a href="http://360.optimalegal.co.uk/?page_id=16" title="Dispute resolution">Dispute resolution</a></li>
	</ul>
</li>
	<li class="page_item page-item-21"><a href="http://360.optimalegal.co.uk/?page_id=21" title="Compliance">Compliance</a></li>
</ul>
</li>
<li class="page_item page-item-68"><a href="http://360.optimalegal.co.uk/?page_id=68" title="Our people">Our people</a></li>
<li class="page_item page-item-70"><a href="http://360.optimalegal.co.uk/?page_id=70" title="News and publications">News and publications</a></li>
                </ul> 
             </div><!--end navwrap-->
             
             
    	</div><!-- end head-->
        
        <div id="main"> <div style="z-index:444; position:absolute; right:0;">
 <div id="newsArea">
                	<div id="newsHolder"><h1>Latest News</h1>
					            	
            
			
           <div class="newsItemH">
		   		
				
			   <div class="newsDateH">30.03.2010</div>
			   <div class="newsContH"><h2><a href="http://360.optimalegal.co.uk/?p=247" rel="bookmark" title="Commercial Collector of the Year 2010">Commercial Collector of the Year 2010...</a></h2>Optima Legal’s very own Richard Gibbon has been shortlisted in the Commercial Collector of the...
			   
			   </div>
            
			</div>   
           		
            
			
           <div class="newsItemH">
		   		
				
			   <div class="newsDateH">20.03.2010</div>
			   <div class="newsContH"><h2><a href="http://360.optimalegal.co.uk/?p=241" rel="bookmark" title="Contributory negligence revisited">Contributory negligence revisited...</a></h2>Any lender bringing professional negligence claims against solicitors or surveyors will face allegations...
			   
			   </div>
            
			</div>   
           		
            
			
           <div class="newsItemH">
		   		
				
			   <div class="newsDateH">22.02.2010</div>
			   <div class="newsContH"><h2><a href="http://360.optimalegal.co.uk/?p=383" rel="bookmark" title="New appointment for Optima Legal">New appointment for Optima Legal...</a></h2>Optima Legal is further expanding its senior litigation team. Paul Loveridge joins Optima Legal as an As...
			   
			   </div>
            
			</div>   
           	                    </div>
                	<div id="pubHolder"><h1>Publications</h1>
					            	
           
           <div class="newsItemH">
		   		
				
			   <div class="newsDateH">11.05.2010</div>
			   <div class="newsContH"><h2><a href="http://360.optimalegal.co.uk/?p=536" rel="bookmark" title="Consumer insurance law – affecting all insurance claims">Consumer insurance law – affecting all in...</a></h2>The English and Scottish Law Commissions (“the Commissions”) have submitted to Parliament a joint re...
			   
			   </div>
            
			</div>   
           		
           
           <div class="newsItemH">
		   		
				
			   <div class="newsDateH">11.05.2010</div>
			   <div class="newsContH"><h2><a href="http://360.optimalegal.co.uk/?p=530" rel="bookmark" title="CCA Debts &#8211; Should minimum thresholds be imposed on Orders for Sale?">CCA Debts &#8211; Should minimum thresholds...</a></h2>In February the Ministry of Justice published a consultation paper considering whether a minimum thresho...
			   
			   </div>
            
			</div>   
           	                    		
                    </div>
                    </div> 
 </div>  
 <div id="featured"> 
            
            <div class="featured_item current">
<div class="featured_text">
<h1><a href="http://360.optimalegal.co.uk/?p=247" title="Commercial Collector of the Year 2010" >Commercial Collector of the Year 2010</a></h1>
Optima Legal’s very own Richard Gibbon has been shortlisted in the Commercial Collector of the Year Award at the prestigious Credit Today Awards held in May 2010.
After receiving...</div><!-- end featured_text-->
<div class="featured_image"><!--an image only slide -->
<img src="http://360.optimalegal.co.uk/wp-content/uploads/2010/04/OPT-fp-awards.jpg" width="940" height="459" alt="" />
</div><!-- end featured_image-->
				
				<div class="featured_text2" >
					
                </div>
                
				</div><!-- end featured_item-->
<div class="featured_item ">
<div class="featured_text">
<h1><a href="http://360.optimalegal.co.uk/?p=243" title="Making TCF stick" >Making TCF stick</a></h1>
The voice of consumer rights groups, internet forums and traditional media on perceived unfair treatment of customers by lenders, grows ever louder.
FSA regulated businesses are de...</div><!-- end featured_text-->
<div class="featured_image"><!--an image only slide -->
<img src="http://360.optimalegal.co.uk/wp-content/uploads/2010/04/opt-tcf-emma.jpg" width="940" height="459" alt="" />
</div><!-- end featured_image-->
				
				<div class="featured_text2" >
					
                </div>
                
				</div><!-- end featured_item-->
<div class="featured_item ">
<div class="featured_text">
<h1><a href="http://360.optimalegal.co.uk/?p=241" title="Contributory negligence revisited" >Contributory negligence revisited</a></h1>
Any lender bringing professional negligence claims against solicitors or surveyors will face allegations of contributory negligence by professionals seeking to limit their exposure...</div><!-- end featured_text-->
<div class="featured_image"><!--an image only slide -->
<img src="http://360.optimalegal.co.uk/wp-content/uploads/2010/04/opt-banners-prof.jpg" width="940" height="459" alt="" />
</div><!-- end featured_image-->
				
				<div class="featured_text2" >
					
                </div>
                
				</div><!-- end featured_item-->
<div id="featured_bottom">
<div class="ticker">
<span class='active_ticker'
 ><a href="http://360.optimalegal.co.uk/?p=247"><strong>Latest News:</strong> Commercial Collector of the Year 2010</a></span>
<span  ><a href="http://360.optimalegal.co.uk/?p=243"><strong>Latest News:</strong> Making TCF stick</a></span>
<span  ><a href="http://360.optimalegal.co.uk/?p=241"><strong>Latest News:</strong> Contributory negligence revisited</a></span>
</div><!--end ticker-->
<div class="preview_images">
<a class='current_prev' href="http://360.optimalegal.co.uk/?p=247"><img src="" alt="" height="0px" width="0px" /></a>
<a  href="http://360.optimalegal.co.uk/?p=243"><img src="" alt="" height="0px" width="0px" /></a>
<a  href="http://360.optimalegal.co.uk/?p=241"><img src="" alt="" height="0px" width="0px" /></a>
</div><!-- end preview_images-->
</div><!-- end featured_bottom-->
</div><!-- end featured-->
 
		         
            
          
          



        
 <div id="footerHome">
            		<div id="rssHolder"><a title="Optima Legal RSS2 Feed" href="/?page_id=401"><img border="0" src="http://360.optimalegal.co.uk/wp-content/themes/twicet/images/rss.gif" width="23" align="absmiddle" height="22" /> RSS</a></div>
                    <div id="privacyHolder"><a href="/?page_id=294">Careers</a>   &nbsp;&nbsp;|&nbsp;&nbsp;   <a href="/?page_id=262">Contact</a>   &nbsp;&nbsp;|&nbsp;&nbsp;  <a href="/?page_id=286">Legal notices</a></div>
  </div>
            <div id="btmLinks">
       		  <div id="regHolder"><p>Regulated by the Solicitors Regulation Authority in accordance with the Solicitors Code of Conduct which can be viewed at <a href="http://www.sra.org.uk" target="_blank">www.sra.org.uk</a></p>
           		    <strong>Case Tracking</strong> &nbsp; <a href="/?page_id=348"><img align="absmiddle" src="http://360.optimalegal.co.uk/wp-content/themes/twicet/images/signIn.gif" width="61" height="16" alt="Sign In" /></a></div>
                    <div id="accHolder"><a href="/?page_id=2"><img src="http://360.optimalegal.co.uk/wp-content/themes/twicet/images/chambers.gif" border="0" width="102" height="45" alt="Chambers" /></a><a href="/?page_id=2"><img src="http://360.optimalegal.co.uk/wp-content/themes/twicet/images/legal_500.gif" width="45" height="45" alt="Legal 500" border="0" /></a></div>
                    
 </div><!--end main-->       
    </div><!--end top-->
</div><!--end wrapp_all-->
<script type='text/javascript'>
/* <![CDATA[ */
var emailL10n = {
	ajax_url: "http://360.optimalegal.co.uk/wp-content/plugins/wp-email/wp-email.php",
	max_allowed: "1",
	text_error: "The Following Error Occurs:",
	text_name_invalid: "- Your Name is empty/invalid",
	text_email_invalid: "- Your Email is empty/invalid",
	text_remarks_invalid: "- Your Remarks is invalid",
	text_friend_names_empty: "- Friend Name(s) is empty",
	text_friend_name_invalid: "- Friend Name is empty/invalid: ",
	text_max_friend_names_allowed: "- Maximum 1 Friend Name allowed",
	text_friend_emails_empty: "- Friend Email(s) is empty",
	text_friend_email_invalid: "- Friend Email is invalid: ",
	text_max_friend_emails_allowed: "- Maximum 1 Friend Email allowed",
	text_friends_tally: "- Friend Name(s) count does not tally with Friend Email(s) count",
	text_image_verify_empty: "- Image Verification is empty"
};
/* ]]> */
</script>
<script type='text/javascript' src='http://360.optimalegal.co.uk/wp-content/plugins/wp-email/email-js.js?ver=2.50'></script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-16018442-1");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
